"""
persistence/models/event_orm.py — ORM for events and the causal graph

Maps:
- NarrativeEvent → events table
- CausalEdge → event_edges table (the DAG)
- EntityDelta → entity_deltas table
- WorldVariableDelta → world_variable_deltas table
"""

from datetime import datetime
from sqlalchemy import String, Text, Integer, DateTime, Float, ForeignKey, JSON
from sqlalchemy.orm import Mapped, mapped_column, relationship
from typing import Any

from persistence.database import Base


class EventORM(Base):
    """
    Table: events

    Maps NarrativeEvent (the atomic unit of the engine).
    """
    __tablename__ = "events"

    id: Mapped[str] = mapped_column(String(36), primary_key=True)
    commit_id: Mapped[str] = mapped_column(
        String(36),
        ForeignKey("commits.id", ondelete="CASCADE"),
        nullable=False
    )

    event_type: Mapped[str] = mapped_column(String(50), nullable=False)
    narrative_text: Mapped[str] = mapped_column(Text, nullable=False)
    summary: Mapped[str] = mapped_column(Text, nullable=False)

    # Decision that triggered this event (None if it was forced)
    triggered_by_decision: Mapped[str | None] = mapped_column(Text, nullable=True)

    # Causal reason generated by the AI (why this event occurs)
    causal_reason: Mapped[str | None] = mapped_column(Text, nullable=True)

    # If this is a FORCED event, which meter triggered it
    forced_by_meter: Mapped[str | None] = mapped_column(String(50), nullable=True)

    # Narrative metadata
    depth: Mapped[int] = mapped_column(Integer, nullable=False)
    topo_order: Mapped[int] = mapped_column(Integer, default=0)

    created_at: Mapped[datetime] = mapped_column(DateTime, nullable=False, default=datetime.now)

    # Relationships
    commit: Mapped["CommitORM"] = relationship("CommitORM", back_populates="events")

    # Outgoing causal edges (this event caused others)
    causal_children: Mapped[list["CausalEdgeORM"]] = relationship(
        "CausalEdgeORM",
        foreign_keys="CausalEdgeORM.cause_event_id",
        back_populates="cause_event",
        cascade="all, delete-orphan"
    )

    # Incoming causal edges (other events caused this one)
    causal_parents: Mapped[list["CausalEdgeORM"]] = relationship(
        "CausalEdgeORM",
        foreign_keys="CausalEdgeORM.effect_event_id",
        back_populates="effect_event",
        cascade="all, delete-orphan"
    )

    entity_deltas: Mapped[list["EntityDeltaORM"]] = relationship(
        "EntityDeltaORM",
        back_populates="event",
        cascade="all, delete-orphan"
    )

    entity_creations: Mapped[list["EntityCreationORM"]] = relationship(
        "EntityCreationORM",
        back_populates="event",
        cascade="all, delete-orphan"
    )

    world_deltas: Mapped[list["WorldVariableDeltaORM"]] = relationship(
        "WorldVariableDeltaORM",
        back_populates="event",
        cascade="all, delete-orphan"
    )

    def __repr__(self) -> str:
        return f"<EventORM(id={self.id[:8]}..., type={self.event_type}, depth={self.depth})>"


class CausalEdgeORM(Base):
    """
    Table: event_edges

    Maps CausalEdge. Represents the causal DAG: A → B.

    CRITICAL CONSTRAINT: before inserting A→B, verify that B→...→A does NOT exist
    (this is done with the recursive CTE in queries/causal_queries.py).
    """
    __tablename__ = "event_edges"

    id: Mapped[str] = mapped_column(String(36), primary_key=True)

    cause_event_id: Mapped[str] = mapped_column(
        String(36),
        ForeignKey("events.id", ondelete="CASCADE"),
        nullable=False
    )
    effect_event_id: Mapped[str] = mapped_column(
        String(36),
        ForeignKey("events.id", ondelete="CASCADE"),
        nullable=False
    )

    relation_type: Mapped[str] = mapped_column(String(50), default="direct")
    strength: Mapped[float] = mapped_column(Float, default=1.0)

    created_at: Mapped[datetime] = mapped_column(DateTime, nullable=False, default=datetime.now)

    # Relationships
    cause_event: Mapped["EventORM"] = relationship(
        "EventORM",
        foreign_keys=[cause_event_id],
        back_populates="causal_children"
    )
    effect_event: Mapped["EventORM"] = relationship(
        "EventORM",
        foreign_keys=[effect_event_id],
        back_populates="causal_parents"
    )

    def __repr__(self) -> str:
        return (
            f"<CausalEdgeORM({self.cause_event_id[:8]}... "
            f"→{self.relation_type}→ "
            f"{self.effect_event_id[:8]}...)>"
        )


class EntityDeltaORM(Base):
    """
    Table: entity_deltas

    Maps EntityDelta. Records changes in entity attributes.
    """
    __tablename__ = "entity_deltas"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)

    event_id: Mapped[str] = mapped_column(
        String(36),
        ForeignKey("events.id", ondelete="CASCADE"),
        nullable=False
    )
    entity_id: Mapped[str] = mapped_column(String(36), nullable=False)
    entity_name: Mapped[str] = mapped_column(String(200), nullable=False)

    attribute: Mapped[str] = mapped_column(String(100), nullable=False)

    # old_value and new_value are JSON because they can be any type
    old_value: Mapped[Any] = mapped_column(JSON, nullable=True)
    new_value: Mapped[Any] = mapped_column(JSON, nullable=True)

    created_at: Mapped[datetime] = mapped_column(DateTime, nullable=False, default=datetime.now)

    # Relationships
    event: Mapped["EventORM"] = relationship("EventORM", back_populates="entity_deltas")

    def __repr__(self) -> str:
        return (
            f"<EntityDeltaORM({self.entity_name}.{self.attribute}: "
            f"{self.old_value} → {self.new_value})>"
        )


class EntityCreationORM(Base):
    """
    Table: entity_creations

    Records which entities were created by which event.
    Audit table for tracking when and how each entity appeared.
    """
    __tablename__ = "entity_creations"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)

    event_id: Mapped[str] = mapped_column(
        String(36),
        ForeignKey("events.id", ondelete="CASCADE"),
        nullable=False
    )
    entity_id: Mapped[str] = mapped_column(String(36), nullable=False)
    entity_name: Mapped[str] = mapped_column(String(200), nullable=False)
    entity_type: Mapped[str] = mapped_column(String(50), nullable=False)
    attributes: Mapped[dict] = mapped_column(JSON, nullable=True, default=dict)

    created_at: Mapped[datetime] = mapped_column(DateTime, nullable=False, default=datetime.now)

    event: Mapped["EventORM"] = relationship("EventORM", back_populates="entity_creations")

    def __repr__(self) -> str:
        return f"<EntityCreationORM({self.entity_name} [{self.entity_type}] by event {self.event_id[:8]}...)>"


class WorldVariableDeltaORM(Base):
    """
    Table: world_variable_deltas

    Maps WorldVariableDelta. Records changes in global world variables.
    """
    __tablename__ = "world_variable_deltas"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)

    event_id: Mapped[str] = mapped_column(
        String(36),
        ForeignKey("events.id", ondelete="CASCADE"),
        nullable=False
    )

    variable: Mapped[str] = mapped_column(String(100), nullable=False)

    old_value: Mapped[Any] = mapped_column(JSON, nullable=True)
    new_value: Mapped[Any] = mapped_column(JSON, nullable=True)

    created_at: Mapped[datetime] = mapped_column(DateTime, nullable=False, default=datetime.now)

    # Relationships
    event: Mapped["EventORM"] = relationship("EventORM", back_populates="world_deltas")

    def __repr__(self) -> str:
        return (
            f"<WorldVariableDeltaORM(world.{self.variable}: "
            f"{self.old_value} → {self.new_value})>"
        )
