"""
engine/state_machine.py — The engine orchestrator (Phase 1: in-memory)

This is the minimal NarrativeRunner: it receives a player decision,
validates that it is coherent, updates the world state, and returns
the new state ready to present to the player.

In Phase 1: everything happens in memory (Python lists and dicts).
In Phase 2: replaced by calls to PostgreSQL repositories.
In Phase 3: the real AI call is added.

The public interface (advance_story) does NOT change between phases.
That is the power of the Repository pattern.
"""

from dataclasses import dataclass, field
from typing import Any

from cne_core.models.world import WorldDefinition, Entity, EntityType
from cne_core.models.event import (
    NarrativeEvent, EventType, EntityDelta, EntityCreation,
    WorldVariableDelta, DramaticDelta, CausalEdge
)
from cne_core.models.commit import NarrativeCommit, NarrativeChoice, Branch
from cne_core.engine.causal_validator import CausalValidator, CausalCycleError
from cne_core.engine.dramatic_engine import DramaticEngine, ForcedEventConstraint


# ── Result of a transition ────────────────────────────────────────────────────

@dataclass
class StoryAdvanceResult:
    """
    What the engine returns after processing a decision.
    This is what the client (API, Flutter, HTML prototype) receives.
    """
    commit:            NarrativeCommit
    narrative_text:    str
    available_choices: list[NarrativeChoice]
    dramatic_state:    dict[str, int]
    forced_event:      ForcedEventConstraint | None = None
    is_ending:         bool = False
    event:             NarrativeEvent | None = None
    causal_edges:      list[CausalEdge] = field(default_factory=list)

    def display(self) -> str:
        """Representation for terminal (useful during development)."""
        lines = [
            f"\n{'=' * 60}",
            f"[CHAPTER {self.commit.depth}]",
            f"{'-' * 60}",
            self.narrative_text,
            f"\n{'-' * 60}",
            f"[DRAMA] Dramatic state: {self._drama_str()}",
        ]

        if self.forced_event:
            lines.append(f"[!] Forced event: {self.forced_event.event_type.value}")

        if not self.is_ending:
            lines.append(f"\n[OPTIONS]:")
            for i, choice in enumerate(self.available_choices, 1):
                preview = choice.get_preview_str()
                preview_str = f"  [{preview}]" if preview else ""
                lines.append(f"  {i}. {choice.text}{preview_str}")

        return "\n".join(lines)

    def _drama_str(self) -> str:
        d = self.dramatic_state
        return (
            f"T={d.get('tension',0)} "
            f"H={d.get('hope',0)} "
            f"C={d.get('chaos',0)} "
            f"M={d.get('mystery',0)}"
        )


# ── StateMachine ───────────────────────────────────────────────────────────────

class StateMachine:
    """
    The narrative engine in its most basic form (Phase 1).

    Manages:
    - The current world state (in memory)
    - The causal event graph
    - The dramatic vector
    - The commit tree (the versioned story)

    Everything in memory: creating a new instance starts the story
    from scratch. In Phase 2, state is persisted in PostgreSQL.
    """

    def __init__(self, world: WorldDefinition):
        self.world = world

        # World state in memory
        self._entities: dict[str, Entity] = {
            e.id: e for e in world.initial_entities
        }
        self._world_variables: dict[str, Any] = {}

        # Causal graph
        self._causal_validator = CausalValidator()

        # Dramatic system initialized with the seed config
        self._dramatic_engine = DramaticEngine(world.dramatic_config)

        # Commit tree (the versioned story)
        self._commits: dict[str, NarrativeCommit] = {}
        self._current_commit_id: str | None = None
        self._events: dict[str, NarrativeEvent] = {}

        # Active branches
        self._branches: dict[str, Branch] = {}

        # Current depth
        self._current_depth: int = 0

    # ── Public API ────────────────────────────────────────────────────────────

    def start(
        self,
        initial_narrative: str,
        initial_choices: list[NarrativeChoice],
        initial_summary: str = "The story begins.",
        initial_dramatic_delta: DramaticDelta | None = None,
        causal_reason: str | None = None,
    ) -> StoryAdvanceResult:
        """
        Initializes the story with the first chapter.

        In Phase 3, this will be generated by the AI. In Phase 1, it is passed
        manually to test the engine.

        Args:
            initial_narrative: The text of the first chapter.
            initial_choices:   The initial options.
            initial_summary:   Summary for the active trunk.
            initial_dramatic_delta: Initial changes to the vector.

        Returns:
            StoryAdvanceResult with the initial state.
        """
        # Create initial event
        if initial_dramatic_delta:
            self._dramatic_engine.apply_delta(initial_dramatic_delta)

        event = NarrativeEvent(
            commit_id      = "pending",   # updated below
            event_type     = EventType.DECISION,
            narrative_text = initial_narrative,
            summary        = initial_summary,
            causal_reason  = causal_reason,
            dramatic_delta = initial_dramatic_delta or DramaticDelta(),
            depth          = 0,
        )
        self._causal_validator.add_event(event.id)
        event.topo_order = self._causal_validator.get_topo_order(event.id)

        # Create initial commit
        commit = NarrativeCommit(
            world_id       = self.world.id,
            event_id       = event.id,
            depth          = 0,
            narrative_text = initial_narrative,
            summary        = initial_summary,
            dramatic_snapshot    = self._dramatic_engine.current_state.copy(),
            world_state_snapshot = self._world_variables.copy(),
            entity_states        = self._get_entity_states(),
        )

        event.commit_id = commit.id
        self._events[event.id]    = event
        self._commits[commit.id]  = commit
        self._current_commit_id   = commit.id

        return StoryAdvanceResult(
            commit            = commit,
            narrative_text    = initial_narrative,
            available_choices = initial_choices,
            dramatic_state    = self._dramatic_engine.current_state.copy(),
            event             = event,
        )

    def advance_story(
        self,
        choice_text:      str,
        narrative_text:   str,
        summary:          str,
        choices:          list[NarrativeChoice],
        entity_deltas:    list[EntityDelta]       | None = None,
        entity_creations: list[EntityCreation]    | None = None,
        world_deltas:     list[WorldVariableDelta] | None = None,
        dramatic_delta:   DramaticDelta | None = None,
        is_ending:        bool = False,
        causal_reason:    str | None = None,
    ) -> StoryAdvanceResult:
        """
        Processes a player decision and advances the story.

        In Phase 1: receives the already generated narrative (manual or mock).
        In Phase 3: will call the AI to generate narrative, then
                   applies validation and persistence.

        Args:
            choice_text:    The option the player chose.
            narrative_text: The narrative text for this moment.
            summary:        1-sentence summary for the trunk.
            choices:        The next available options.
            entity_deltas:  Entity changes caused by this event.
            world_deltas:   Changes to global variables.
            dramatic_delta: Changes to the dramatic vector.
            is_ending:      Is this the end of the story?

        Returns:
            StoryAdvanceResult with the new state.

        Raises:
            RuntimeError: If the story has not been started.
            ValueError:   If the story has already reached its depth limit.
        """
        if self._current_commit_id is None:
            raise RuntimeError("Call start() before advance_story()")

        # Check depth limit
        if self.world.max_depth > 0 and self._current_depth >= self.world.max_depth:
            raise ValueError(
                f"Story reached maximum depth ({self.world.max_depth}). "
                f"Use is_ending=True in the last advance_story()."
            )

        self._current_depth += 1
        current_commit = self._commits[self._current_commit_id]

        # 1. Create new entities (before deltas, so deltas can reference them)
        entity_creations = entity_creations or []
        self._apply_entity_creations(entity_creations, self._current_depth)

        # 2. Apply entity deltas
        entity_deltas = entity_deltas or []
        self._apply_entity_deltas(entity_deltas)

        # 3. Apply global variable deltas
        world_deltas = world_deltas or []
        self._apply_world_deltas(world_deltas)

        # 4. Update the dramatic vector
        dramatic_delta = dramatic_delta or DramaticDelta()
        self._dramatic_engine.apply_delta(dramatic_delta)

        # 5. Evaluate if thresholds are crossed -> forced event
        forced_constraint = self._dramatic_engine.evaluate_thresholds()

        # 6. Create the narrative event
        event = NarrativeEvent(
            commit_id              = "pending",
            event_type             = EventType.FORCED if forced_constraint else EventType.DECISION,
            narrative_text         = narrative_text,
            summary                = summary,
            triggered_by_decision  = choice_text,
            causal_reason          = causal_reason,
            caused_by              = [current_commit.event_id],
            entity_deltas          = entity_deltas,
            entity_creations       = entity_creations,
            world_deltas           = world_deltas,
            dramatic_delta         = dramatic_delta,
            forced_by_meter        = (
                forced_constraint.trigger_meter if forced_constraint else None
            ),
            depth                  = self._current_depth,
        )

        # 8. Register in the causal graph and validate
        self._causal_validator.add_event(event.id)
        causal_edge = CausalEdge(
            cause_event_id=current_commit.event_id,
            effect_event_id=event.id,
        )
        try:
            self._causal_validator.add_edge(
                current_commit.event_id,
                event.id
            )
        except CausalCycleError as e:
            raise

        event.topo_order = self._causal_validator.get_topo_order(event.id)

        # 9. Create the new commit
        new_commit = NarrativeCommit(
            world_id         = self.world.id,
            event_id         = event.id,
            depth            = self._current_depth,
            parent_id        = self._current_commit_id,
            choice_text      = choice_text,
            narrative_text   = narrative_text,
            summary          = summary,
            branch_id        = current_commit.branch_id,
            is_ending        = is_ending,
            dramatic_snapshot    = self._dramatic_engine.current_state.copy(),
            world_state_snapshot = self._world_variables.copy(),
            entity_states        = self._get_entity_states(),
        )

        event.commit_id = new_commit.id

        # 10. Register commit and update pointers
        current_commit.add_child(new_commit.id)
        self._events[event.id]       = event
        self._commits[new_commit.id] = new_commit
        self._current_commit_id      = new_commit.id

        return StoryAdvanceResult(
            commit            = new_commit,
            narrative_text    = narrative_text,
            available_choices = choices if not is_ending else [],
            dramatic_state    = self._dramatic_engine.current_state.copy(),
            forced_event      = forced_constraint,
            is_ending         = is_ending,
            event             = event,
            causal_edges      = [causal_edge],
        )

    def go_to_commit(self, commit_id: str) -> StoryAdvanceResult:
        """
        Returns to a previous commit (branch navigation).

        Restores the complete world state at that point,
        including the dramatic vector.
        """
        if commit_id not in self._commits:
            raise ValueError(f"Commit {commit_id[:8]}... does not exist")

        commit = self._commits[commit_id]

        # Restore dramatic vector
        self._dramatic_engine.vector.from_dict(commit.dramatic_snapshot)

        # Restore global variables
        self._world_variables = commit.world_state_snapshot.copy()

        # Restore entities (simplified for Phase 1)
        # In Phase 2 this will use the StateRebuilder with real deltas
        self._restore_entity_states(commit.entity_states)

        self._current_commit_id = commit_id
        self._current_depth     = commit.depth

        return StoryAdvanceResult(
            commit            = commit,
            narrative_text    = commit.narrative_text,
            available_choices = [],   # Will be regenerated in Phase 3
            dramatic_state    = commit.dramatic_snapshot.copy(),
        )

    # ── Reconstruction from DB ──────────────────────────────────────────────

    def rebuild_from_commits(self, commits: list[NarrativeCommit]) -> None:
        """
        Rebuilds the engine state from a list of commits (loaded from DB).

        Registers each commit in the tree, reconstructs the causal graph,
        and restores the world state from the latest commit.

        Args:
            commits: List of NarrativeCommit in chronological order (oldest first).
        """
        if not commits:
            return

        for commit in commits:
            self._commits[commit.id] = commit

            # Generate synthetic event_id if missing (events not saved to DB yet)
            if not commit.event_id:
                commit.event_id = f"synth-{commit.id}"

            self._causal_validator.add_event(commit.event_id)

            if commit.parent_id and commit.parent_id in self._commits:
                parent = self._commits[commit.parent_id]
                if commit.id not in parent.children_ids:
                    parent.add_child(commit.id)
                if parent.event_id and commit.event_id:
                    try:
                        self._causal_validator.add_edge(
                            parent.event_id,
                            commit.event_id
                        )
                    except CausalCycleError:
                        pass

        latest = commits[-1]
        self._current_commit_id = latest.id
        self._current_depth = latest.depth

        if latest.dramatic_snapshot:
            self._dramatic_engine.vector.from_dict(latest.dramatic_snapshot)

        if latest.world_state_snapshot:
            self._world_variables = latest.world_state_snapshot.copy()

        if latest.entity_states:
            self._restore_entity_states(latest.entity_states)

    # ── Queries ────────────────────────────────────────────────────────────────

    def get_current_commit(self) -> NarrativeCommit | None:
        if self._current_commit_id:
            return self._commits.get(self._current_commit_id)
        return None

    def get_trunk_summary(self, max_recent: int = 6) -> str:
        """
        Builds the 'active trunk' to send to the AI.

        Recent commits are shown in detail.
        Earlier ones are compressed to 1 line each.
        """
        if not self._current_commit_id:
            return ""

        # Collect the chain of commits up to the current one
        chain: list[NarrativeCommit] = []
        cid = self._current_commit_id
        while cid:
            commit = self._commits.get(cid)
            if not commit:
                break
            chain.append(commit)
            cid = commit.parent_id

        chain.reverse()   # Chronological order

        lines = []
        recent_start = max(0, len(chain) - max_recent)

        # Compressed old commits
        if recent_start > 0:
            lines.append("[COMPRESSED EARLIER HISTORY]")
            for commit in chain[:recent_start]:
                if commit.summary:
                    lines.append(commit.to_trunk_entry())

        # Recent commits with detail
        lines.append("\n[RECENT CHAPTERS]")
        for commit in chain[recent_start:]:
            lines.append(commit.to_trunk_entry())

        return "\n".join(lines)

    def get_causal_stats(self) -> dict:
        """Causal graph statistics (for the paper)."""
        return self._causal_validator.get_stats()

    def get_dramatic_arc_analysis(self) -> dict:
        """Dramatic arc analysis (for the paper)."""
        return self._dramatic_engine.get_arc_analysis()

    # ── Private helpers ───────────────────────────────────────────────────────

    def _apply_entity_creations(self, creations: list[EntityCreation], depth: int) -> None:
        """Creates new entities and registers them in the world state."""
        for creation in creations:
            entity_type_map = {
                "character": EntityType.CHARACTER,
                "faction": EntityType.FACTION,
                "artifact": EntityType.ARTIFACT,
                "location": EntityType.LOCATION,
            }
            etype = entity_type_map.get(creation.entity_type.lower(), EntityType.CHARACTER)
            entity = Entity(
                id=creation.entity_id,
                name=creation.entity_name,
                entity_type=etype,
                attributes={
                    **creation.attributes,
                    "created_at_depth": depth,
                },
            )
            self._entities[entity.id] = entity

    def _apply_entity_deltas(self, deltas: list[EntityDelta]) -> None:
        for delta in deltas:
            entity = self._entities.get(delta.entity_id)
            if entity:
                entity.attributes[delta.attribute] = delta.new_value

    def _apply_world_deltas(self, deltas: list[WorldVariableDelta]) -> None:
        for delta in deltas:
            self._world_variables[delta.variable] = delta.new_value

    def _get_entity_states(self) -> dict[str, Any]:
        """Snapshot of the current state of all entities."""
        return {
            eid: {
                "name":       e.name,
                "type":       e.entity_type.value,
                "attributes": e.attributes.copy(),
                "alive":      e.is_alive,
                "created_at_depth": e.attributes.get("created_at_depth", 0),
            }
            for eid, e in self._entities.items()
        }

    def _restore_entity_states(self, states: dict[str, Any]) -> None:
        """Restores entity state from a snapshot (full reconstruction)."""
        self._entities.clear()
        for eid, state in states.items():
            entity_type_map = {
                "character": EntityType.CHARACTER,
                "faction": EntityType.FACTION,
                "artifact": EntityType.ARTIFACT,
                "location": EntityType.LOCATION,
            }
            etype = entity_type_map.get(state.get("type", "character"), EntityType.CHARACTER)
            entity = Entity(
                id=eid,
                name=state.get("name", "Unknown"),
                entity_type=etype,
                attributes=state.get("attributes", {}).copy(),
            )
            self._entities[entity.id] = entity
